//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LIMSDBEntities : DbContext
    {
        public LIMSDBEntities()
            : base("name=LIMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Department> T_Department { get; set; }
        public DbSet<T_MemberInformation> T_MemberInformation { get; set; }
        public DbSet<T_Organization> T_Organization { get; set; }
        public DbSet<T_ProjectType> T_ProjectType { get; set; }
        public DbSet<T_ProjPhase> T_ProjPhase { get; set; }
        public DbSet<T_TaskInformation> T_TaskInformation { get; set; }
        public DbSet<T_TaskParticipation> T_TaskParticipation { get; set; }
        public DbSet<T_TaskType> T_TaskType { get; set; }
        public DbSet<T_TechnicaLevel> T_TechnicaLevel { get; set; }
        public DbSet<T_ProjectInformation> T_ProjectInformation { get; set; }
        public DbSet<T_ProjectParticipation> T_ProjectParticipation { get; set; }
        public DbSet<T_Role> T_Role { get; set; }
        public DbSet<T_RoleAct> T_RoleAct { get; set; }
        public DbSet<T_RolePermission> T_RolePermission { get; set; }
        public DbSet<T_Permission> T_Permission { get; set; }
    }
}
